<a href="https://colab.research.google.com/github/srilalithaveerubhotla/CMPE_258/blob/master/Numpy_Array_Examples.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy Plays**
   ### **a) Creation Types,Dimensions & Data types**
   ### **a) Arithmetic & Boolean Operations**
   ### **b) Reshaping,Arranging & Matrices**
   ### **c) Sorting,Searching & Counting Functions**
   ### **d) Slicing,Indexing,Transposing**
   ### **e) Joining,Splitting**
   ### **f) Exponents,Logarithms & Trignometric Functions**
   ### **g) Statistical Operations**
   ### **h) Broadcasting**
   ### **i) Linear Algebra**


In [0]:
import numpy as np
np.random.seed(0)

In [0]:
np.empty([4,4],dtype=float)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [0]:
np.zeros([4,4],dtype=float)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [0]:
np.ones([4,4],dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [0]:
np.random.randint(25, size=9)

array([ 7,  9, 19, 21, 18,  4, 23,  6, 24])

In [0]:
np.random.randint(25,size=(2,2))

array([[24, 12],
       [ 1,  6]])

In [0]:
np.random.randint(25,size=(3,3))

array([[ 7, 23, 14],
       [24, 17,  5],
       [13,  8,  9]])

In [0]:
np.random.randint(25,size=(2,3,3))

array([[[20, 17, 15],
        [ 4,  9, 10],
        [24,  1,  1]],

       [[ 7,  9,  3],
        [ 6, 23, 11],
        [14, 18,  0]]])

In [0]:
np.random.randint(25,size=(2,3,3)).size #  size is always the multiplied output of the mentioned 

18

In [0]:
np.random.randint(25,size=(2,3,3)).ndim #  size is always the multiplied output of the mentioned 

3

In [0]:
np.random.randint(25,size=(2,3,3,4)).size #  size is always the multiplied output of the mentioned 

72

In [0]:
np.random.randint(25,size=(2,3,4,3)).ndim #  size is always the multiplied output of the mentioned 

4

In [0]:
np.arange(10) # Ranging numbers

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
np.arange(13,30) # Ranging start and end

array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [0]:
np.arange(13,30,4) # With a difference we get

array([13, 17, 21, 25, 29])

In [0]:
np.linspace(20,30,5) # With a factional difference we get a result

array([20. , 22.5, 25. , 27.5, 30. ])

In [0]:
np.linspace(1,2,5,retstep=True) # With a factional difference of 0.25 we get a result

(array([1.  , 1.25, 1.5 , 1.75, 2.  ]), 0.25)

In [0]:
np.logspace(10,20,num=2,base=2) # With a logarithmic difference of the given numbers array is formed.

array([1.024000e+03, 1.048576e+06])

In [0]:
a=np.array([1,2,3,4,5])
print(a+1) 
print(a-1) 
print(a*2) 
print(a/2) 

[2 3 4 5 6]
[0 1 2 3 4]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]


In [0]:
a=np.random.randint((10,30),size=(2,2))
print(a)
print(a+1) 
print(a-1) 
print(a*2) 
print(a/2)

[[ 9 28]
 [ 1  9]]
[[10 29]
 [ 2 10]]
[[ 8 27]
 [ 0  8]]
[[18 56]
 [ 2 18]]
[[ 4.5 14. ]
 [ 0.5  4.5]]


In [0]:
a=np.linspace(10,20,8)
print(a)
print(a+1) 
print(a-1) 
print(a*2) 
print(a/2)

[10.         11.42857143 12.85714286 14.28571429 15.71428571 17.14285714
 18.57142857 20.        ]
[11.         12.42857143 13.85714286 15.28571429 16.71428571 18.14285714
 19.57142857 21.        ]
[ 9.         10.42857143 11.85714286 13.28571429 14.71428571 16.14285714
 17.57142857 19.        ]
[20.         22.85714286 25.71428571 28.57142857 31.42857143 34.28571429
 37.14285714 40.        ]
[ 5.          5.71428571  6.42857143  7.14285714  7.85714286  8.57142857
  9.28571429 10.        ]


In [0]:
a=np.random.randint(12,size=10)
b=np.linspace(10,20,10)
print(a)
print(b)
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[ 0 10  3 10  1 10  9  9  6  6]
[10.         11.11111111 12.22222222 13.33333333 14.44444444 15.55555556
 16.66666667 17.77777778 18.88888889 20.        ]
[10.         21.11111111 15.22222222 23.33333333 15.44444444 25.55555556
 25.66666667 26.77777778 24.88888889 26.        ]
[-10.          -1.11111111  -9.22222222  -3.33333333 -13.44444444
  -5.55555556  -7.66666667  -8.77777778 -12.88888889 -14.        ]
[  0.         111.11111111  36.66666667 133.33333333  14.44444444
 155.55555556 150.         160.         113.33333333 120.        ]
[0.         0.9        0.24545455 0.75       0.06923077 0.64285714
 0.54       0.50625    0.31764706 0.3       ]


In [0]:
a=np.random.randint(12,size=(2,2))
print(a)
print(np.reciprocal(a))
print(np.power(a,2))
print(np.real(a))
print(np.conjugate(a))
print(np.imag(a))
print(np.angle(a))

[[ 5  9]
 [ 7 11]]
[[0 0]
 [0 0]]
[[ 25  81]
 [ 49 121]]
[[ 5  9]
 [ 7 11]]
[[ 5  9]
 [ 7 11]]
[[0 0]
 [0 0]]
[[0. 0.]
 [0. 0.]]


## Dimensions and shape check 

In [0]:
c=np.random.randint(25,size=(2,3,3))

In [0]:
print("c ndim: ", c.ndim)
print("c shape:", c.shape)
print("c size: ", c.size)

c ndim:  3
c shape: (2, 3, 3)
c size:  18
